Skios xx backlog tim
skiosa/documentation pull request #11
Opened 2022-04-22 08:22 UTC by eintim

# Skiosa - PR
- [ x ] documentation can't be split up into smaller logical units
- [ ] PRE-MERGE add tag to start drone automation

2022-04-22 08:32 UTC, grossamos approved these changes
not much to say, lgtm

2022-04-22 12:02 UTC, jeppard requested changes
Please rebase on master to resolve merge conflicts

2022-04-25 11:59 UTC, LukasLJL commented
@jeppard should be fixed now.

2022-04-25 12:03 UTC, jeppard approved these changes

2022-04-25 12:04 UTC, merged