Text erstellt version 1.0
skiosa/documentation pull request #46
Opened 2022-05-10 19:24 UTC by Y05h129

# Skiosa - PR
- [x] documentation can't be split up into smaller logical units
- [ ] PRE-MERGE add tag to start drone automation

2022-05-10 20:47 UTC, grossamos commented
PR name go BRRRRRRRRRRR

2022-05-10 20:56 UTC, grossamos requested changes

2022-05-10 20:56 UTC, grossamos commented on content/06kapitel.tex
> +In der ersten Planungsbesprechung haben wir sehr viel Zeit für die Kapazitätschätzung benötigt.
```suggestion
Innerhalb des Ersten Sprintes haben wir sehr viel Zeit für die Kapazitätschätzung benötigt. 
Dies hatte zur Folge, dass im Sprint Planning kaum Zeit für Produktive Diskussionen übrig war und mit laufender Dauer die Konzentration für Estimations abnahm.
```

2022-05-10 20:56 UTC, grossamos commented on content/06kapitel.tex
> +Daher haben wir beschlossen diese auszulagern und sie in unser Bi-Weekly zu verschieben.
```suggestion
Daher haben wir beschlossen das Estimation Meeting vom Sprint Planning zu entkoppeln. So kamen zu den den Bi-Weeklys und ungenutzten Vorlesungsterminen das neue Estimation Meeting hinzu.
```

2022-05-10 20:56 UTC, grossamos commented on content/06kapitel.tex
> +Dies führte im positiven dazu, dass die Estimations spezifischer und zielgerichteter statt fanden.
```suggestion
Dies führte dazu, dass im Planning Meeting nun genügend Zeit war und die Qualität der Estimations zunahm, was sich in den Burndown-Charts reflektiert.
```

2022-05-10 20:56 UTC, grossamos commented on content/06kapitel.tex
> +Darüber hinaus waren die Schätzungen nicht genau genug, bzw. die Konzentrantionskapazitäten ausgeschöpft.
line bitte löschen

2022-05-10 20:56 UTC, grossamos commented on content/06kapitel.tex
> +\subsection{Ausgliederung der Kapazitätsschätzungen aus den Planungsbesprechungen}
```suggestion
\subsection{Ausgliederung der Estimations aus den Planungsbesprechungen}
```

2022-05-10 20:56 UTC, grossamos commented on content/06kapitel.tex
> +\subsection{Ausgliederung der Kapazitätsschätzungen aus den Planungsbesprechungen}
I KNOW; ABER HIER MUSSS ENGLISCH, sonst kriegt der PO einen raster

2022-05-11 06:30 UTC, Y05h129 commented on content/06kapitel.tex
> +\subsection{Ausgliederung der Kapazitätsschätzungen aus den Planungsbesprechungen}
Theo hat das auch nicht so

2022-05-11 10:44 UTC, Y05h129 commented on content/06kapitel.tex
> +Darüber hinaus waren die Schätzungen nicht genau genug, bzw. die Konzentrantionskapazitäten ausgeschöpft.
-> line17

2022-05-11 10:54 UTC, grossamos approved these changes

2022-05-11 10:54 UTC, merged