Final Documentation PR
skiosa/documentation pull request #57
Opened 2022-05-14 22:14 UTC by grossamos

This is the changelog for the final documenation.

Please check:
- [ ] That your story point count is correct
- [ ] You are happy with your ``sonstige Beiträge``
- [ ] You couldn't find any more Spelling mistakes

Note @jeppard , Requirements was chosen instead of ``Anforderungen``, because this was the term used by Garidis

2022-05-15 10:12 UTC, LukasLJL commented
Maybe delete ``Formelverzeichnis`` & ``Listings``.
In Figura 2.1 ``Jonas Eppart`` -> ``Jonas Eppard``
There is an empty Page at B (119), G (124)
Max. Page Counter is wrong I guess.

2022-05-15 18:56 UTC, eintim requested changes

2022-05-15 18:56 UTC, eintim commented on content/06kapitel.tex
> +    Jonas Eppard & 47 & Recomendation und ORM service Lead\\
Jonas has 61 Points

2022-05-15 18:56 UTC, eintim commented on content/06kapitel.tex
> +    Sabrina Ladner & 16 & Scrum Master\\
Sabrina has 25 Points

2022-05-15 18:56 UTC, eintim commented on content/06kapitel.tex
> +    Theo Krinitz & 19 & N. A.\\
Theo has 21 Points

2022-05-15 18:56 UTC, eintim commented on content/06kapitel.tex
> +    Tim Horlacher & 61 & Architekt und Core Service Lead, hat ein Großteil der Backend/Infra Stories Reviewed\\
Tim has 64 Points

2022-05-15 18:56 UTC, eintim commented on content/06kapitel.tex
> +    Sophie Gösch & 15 & N. A.\\
Sophie has 17 Points

2022-05-15 18:56 UTC, eintim commented on content/06kapitel.tex
> +    Amos Groß & 54 & Projekt Organisation, Ersteller der User Stories und Product Owner\\
Amos has 57 Points

2022-05-15 18:56 UTC, eintim commented on content/06kapitel.tex
> +    Marcel Alex & 24 & N. A.\\
Marcel has 21 Points

2022-05-15 18:56 UTC, eintim commented on content/06kapitel.tex
> +    Simon Morgenstern & 20 & Front-end Service Lead, hat ein Großteil der Frontend Stories Reviewed\\
Simon has 25 Points

2022-05-15 19:00 UTC, eintim requested changes

2022-05-15 19:00 UTC, eintim commented on content/06kapitel.tex
> +    Lukas Huida & 88 & Archtiekt, Organisation der \enquote{bare metal}-infra und server\\
Lukas has 91

2022-05-15 19:15 UTC, eintim commented on content/06kapitel.tex
> +    Marcel Alex & 24 & N. A.\\
One story was assigned to amos nvm

2022-05-15 19:16 UTC, eintim commented on content/06kapitel.tex
> +    Amos Groß & 54 & Projekt Organisation, Ersteller der User Stories und Product Owner\\
marcel did one story

2022-05-17 20:34 UTC, Y05h129 approved these changes

2022-05-18 05:38 UTC, merged