Added PR Template
skiosa/documentation pull request #6
Opened 2022-04-14 08:45 UTC by LukasLJL

# Skiosa - PR
- [x] documentation can't be split up into smaller logical units
- [x] document is formated

2022-04-14 10:55 UTC, jeppard requested changes
Add Latexindent that latex document can be formated

2022-04-14 10:55 UTC, jeppard commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] document is formated
Latexindent not working

2022-04-14 11:04 UTC, LukasLJL commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] document is formated
removed from template

2022-04-15 08:56 UTC, jeppard reviewed
lgtm

2022-04-15 08:57 UTC, jeppard approved these changes

2022-04-15 08:57 UTC, merged